name: build docker image and push to registry

on:
  push:
    branches: ["main"]

jobs:
  docker:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitLab
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{secrets.GITLAB_USERNAME}}
          password: ${{secrets.GITLAB_PASSWORD}}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: registry.gitlab.com/ronalmog/realio:1.2
